unstable_features = true
match_block_trailing_comma = true
trailing_comma = "Vertical"
condense_wildcard_suffixes = true
struct_field_align_threshold = 999
enum_discrim_align_threshold = 999
imports_granularity = "Crate"
max_width = 120
